# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7db9ec5d6ffcae95082f5c72560a9ad0da80e90bbee6e2da4a648dd3ec7c6f559b3779e615af1452e80fc69323df601686bf71a023de5cc9b96de9757915fccf

test:
  secret_key_base: a8a78300c2c90fa9213d2b3b75e288f43360c7796dee13df3bb19ad0d7f6d9ef7cd231b1f064e36bd5124c9c68ef970ca24a0c5f79a1c5d2876c7ff5184d6d79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
